// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtUsk6FKcoMT3fyDJJwZ6Ad81Ifefl-M',
    appId: '1:410574757990:android:c6cea467c970822551cda7',
    messagingSenderId: '410574757990',
    projectId: 'storageapp-9a33b',
    storageBucket: 'storageapp-9a33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLvCvm-6O6d-VxSFIPWVSak2oPkpRndw',
    appId: '1:410574757990:ios:b68070199cb602e651cda7',
    messagingSenderId: '410574757990',
    projectId: 'storageapp-9a33b',
    storageBucket: 'storageapp-9a33b.firebasestorage.app',
    iosBundleId: 'com.example.agrimix',
  );
}